### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by johannphilippe** [univrsal/libgamepad#4]
Hello, 
Thanks for this great llibrary. 
Any chance to see a MacOS support ? 
Thanks !

**Comment by johannphilippe** [comment]
```cmake
elseif (APPLE)
    target_sources(gamepad PRIVATE
        ./src/darwin/hook-darwin.cpp
        )
```
This makes me think a port for MacOS was considered at some point ?

**Comment by univrsal** [comment]
I have decided a while ago that macos is not worth my time. It caused nothing but problems and headaches. So no, I personally will not add macos support.

**Comment by johannphilippe** [comment]
I couldn't agree more. 
I'm just in a work situation where I need a gamepad support for macos...
Thanks anyway for this work
