### ISSUE TITLE
No darwin folder for APPLE

### ISSUE THREAD

**Issue by Mykhalevych** [univrsal/libgamepad#7]
In CMakeList at the 49 line - setted target_sources for APPLE. But darwin folder is absent.

`elseif (APPLE)
    target_sources(gamepad PRIVATE
        ./src/darwin/hook-darwin.cpp
        )`

**Comment by univrsal** [comment]
yeah, it doesn't support macos and it probably never will unless someone else implements it.

**Comment by Mykhalevych** [comment]
Is there are big different it from Linux?

**Comment by univrsal** [comment]
I don't know, but I would assume so.
